### ISSUE TITLE
Metadata Design - Master-Part Relationships

### ISSUE THREAD

**Issue by danielmk** [SFB1089/adamacs#4]
datajoint-elements makes extensive use of the Master-Part Relationships. [Here are the docs](https://docs.datajoint.org/python/computation/03-master-part.html#master-part).
I don't really understand the usecase for the master part. If things are "inseparably associated", why wouldn't I just make them attributes of the entity? An example:
```
@schema
class Subject(dj.Manual):

    definition = """
    # Animal Subject
    subject                 : varchar(32)
    ---
    sex                     : enum('M', 'F', 'U')
    subject_birth_date      : date
    subject_description=''  : varchar(1024)
    """

    class Protocol(dj.Part):
        definition = """
        -> master
        -> Protocol
        """
# Protocol taken from element-lab
@schema
class Protocol(dj.Lookup):
    definition = """
    # protocol approved by some institutions like IACUC, IRB
    protocol                : varchar(16)
    ---
    -> ProtocolType
    protocol_description=''        : varchar(255)
    """
```

If they are inseparable why wouldn't I rewrite this as:

```
class Subject(dj.Manual):

    definition = """
    # Animal Subject
    subject                 : varchar(32)
    ---
    sex                     : enum('M', 'F', 'U')
    subject_birth_date      : date
    subject_description=''  : varchar(1024)
    protocol : varchar(16)
    protocol_description='' :varchar(255)
    -> ProtocolType
    """
```

Is this the relational database equivalent of a function definition, where we can take the protocol that's defined elsewhere?

**Comment by dimitri-yatsenko** [comment]
Indeed, master-part relationships are most meaningful in automatically computed tables where the master populates its parts within an ACID transaction.

In manual and lookup tables, the master-part pattern is still commonly used to communicate that the entries in parts corresponding to the same master must be treated as one inseparable group of entries. But in the case of manual and lookup tables, it's up to the invoking code to observe this convention.

There are several reasons why you might need to spread data from one table into several related tables. In the design above, the reason `Subject.Protocol` exists is to allow multiple protocols per subject because both subject and protocol IDs are in the primary key of `Subject.Protocol`. In this way, `Subject.Protocol` is an association table creating a many-to-many relationship between subjects and protocols. 

`Subject.Protocol` does not need to be a part table. It could be designed as a regular manual or lookup table, e.g. `SubjectProtocol`. Making it part of `Subject` communicates the idea that all protocols must be entered at the time when the subject is entered.
